### PR TITLE
US7.1 add supplier information

### PR DESCRIPTION
**Pull request by alexandregrue**

### CODE REVIEW

**Review by soufcod3 — DISMISSED** [review]
Looks good

**Review by RomainClair — CHANGES_REQUESTED** [review]
migrations are invalid with dev

**Review by soufcod3 — APPROVED** [review]
The new version file looks good

**Review by RomainClair — CHANGES_REQUESTED** [review]
The migration file is still not compatible with what's in the dev branch

**Review by iStyyx — DISMISSED** [review]
Seems to be ok

**Review by RomainClair — CHANGES_REQUESTED** [review]
The migration file is still inconsistent with the dev database state.
Perhaps you should : 
Go back to dev (and assure you have the latest dev version)
Get your database in the correct state (you could drop, create a migrate the db)
The your database is in the dev state
Make the list of all the Version that are here
Then checkout to you new branch, remove all Versions that are not in dev
Then create a new migration file

**Review by iStyyx — APPROVED** [review]

**Review by RomainClair — APPROVED** [review]

**Pull request merged**
